name: base
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - conda=4.6.14
  - cryptography=2.6.1
  - idna=2.8
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=19.0.3
  - pycosat=0.6.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.6.8
  - python=3.7.3
  - readline=7.0
  - requests=2.21.0
  - ruamel_yaml=0.15.46
  - setuptools=41.0.0
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - urllib3=1.24.1
  - wheel=0.33.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - numpy==1.17.1
  - pandas==0.25.0
  - python-dateutil==2.8.0
  - pytz==2019.2
prefix: /home/iarizex/miniconda3

